image:
  registry.gitlab.com/grupo-esfera/capacitacion/recursos/repartir

  # GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_PIPELINE_ID'

stages:
  - test

acceptance-test-js:
  stage: test
  script:
    - npm run acceptance-test --prefix=src/main/frontend

acceptance-test-js:e2e:
  stage: test
  script:
    - npm run acceptance-test:e2e --prefix=src/main/frontend

acceptance-test-js:mock-api:
  stage: test
  script:
    - npm run acceptance-test:mock-api --prefix=src/main/frontend

acceptance-test-js:backend:
  stage: test
  script:
    - npm run acceptance-test:backend --prefix=src/main/frontend
