image: registry.gitlab.com/grupo-esfera/capacitacion/recursos/repartir

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.caching=true"
  # GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_PIPELINE_ID'

stages:
  - build
  - test

build:
  stage: build
  script: echo "hola"
  
trigger-acceptance-test-advanced:
  trigger:
    include:
      - local: .gitlab-ci-assemblies.yml
