image: registry.gitlab.com/grupo-esfera/capacitacion/recursos/repartir

stages:
  - test

acceptance-test:
  stage: test
  before_script:
    - npm ci --prefix src/main/frontend
  script:
    - npm run acceptance-test --prefix=src/main/frontend
  artifacts:
    when: always
    reports:
      junit: build/test-results/acceptanceTestJs/**/TEST-*.xml
    name: acceptance-test-js-coverage
    paths:
      - src/main/frontend/coverage-reports/
      - build/reports/playwright-reports/

acceptance-test-e2e:
  stage: test
  before_script:
    - npm ci --prefix src/main/frontend
  script:
    - npm run acceptance-test:e2e --prefix=src/main/frontend
  artifacts:
    when: always
    reports:
      junit: build/test-results/acceptanceTestJs/**/TEST-*.xml
    name: acceptance-test-js-coverage
    paths:
      - src/main/frontend/coverage-reports/
      - build/reports/playwright-reports/

acceptance-test-mock-api:
  stage: test
  before_script:
    - npm ci --prefix src/main/frontend
  script:
    - npm run acceptance-test:mock-api --prefix=src/main/frontend
  artifacts:
    when: always
    reports:
      junit: build/test-results/acceptanceTestJs/**/TEST-*.xml
    name: acceptance-test-js-coverage
    paths:
      - src/main/frontend/coverage-reports/
      - build/reports/playwright-reports/

acceptance-test-backend:
  stage: test
  before_script:
    - npm ci --prefix src/main/frontend
  script:
    - npm run acceptance-test:backend --prefix=src/main/frontend
  artifacts:
    when: always
    reports:
      junit: build/test-results/acceptanceTestJs/**/TEST-*.xml
    name: acceptance-test-js-coverage
    paths:
      - src/main/frontend/coverage-reports/
      - build/reports/playwright-reports/
