image: registry.gitlab.com/grupo-esfera/capacitacion/recursos/repartir

stages:
  - install
  - test

default:
  before_script:
    - npm ci --prefix src/main/frontend

install:
  stage: install
  script:
    - echo "Instalando dependencias"
    - npm ci --prefix src/main/frontend
  cache:
    key:
      files:
        - src/main/frontend/package-lock.json
      prefix: $CI_COMMIT_REF_SLUG
    paths:
      - src/main/frontend/node_modules

test-assembly:
  stage: test
  script:
    - echo "Ejecutando pruebas"
    - cd src/main/frontend
    - npm test
  cache:
    key:
      files:
        - src/main/frontend/package-lock.json
      prefix: $CI_COMMIT_REF_SLUG
    paths:
      - src/main/frontend/node_modules
  artifacts:
    when: always
    reports:
      junit: build/test-results/**/TEST-*.xml
    paths:
      - build/test-results/

